name: Update Blocklist

on:
  schedule:
    - cron: "0 */6 * * *"   # tiap 6 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: |
          chmod +x merge.sh
          ./merge.sh

      - name: Commit result
        run: |
          git config user.name "blocklist-bot"
          git config user.email "bot@github.com"
          git add merged.txt
          git commit -m "Auto update blocklist" || echo "No changes"
          git push
