name: Update Blocklist

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"   # tiap 6 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run merge script
        run: |
          chmod +x merge.sh
          ./merge.sh

      - name: Commit & push
        run: |
          git config user.name "blocklist-bot"
          git config user.email "bot@github.com"
          git add merged.txt
          git commit -m "Auto update blocklist" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
